version: '3.7'
services:
  infping:
    image: infping
    volumes:
      - ./infping.yaml:/etc/infping.yaml
    hostname: infping
    restart: always
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    volumes:
      - ./db_data:/var/lib/influxdb

  grafana:
    image: fg2it/grafana-armhf:v5.1.4
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
